# roles/jenkins/defaults/main.yml
---
jenkins_key_url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
jenkins_repo_url: "deb https://pkg.jenkins.io/debian-stable binary/"
jenkins_home: /var/lib/jenkins
jenkins_port: 8080
jenkins_user: jenkins
jenkins_group: jenkins
java_package: openjdk-11-jdk