---
galaxy_info:
  author: Your Name
  description: Install Docker Compose
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL  # Enterprise Linux
      versions:
        - 7
        - 8
        - 9
  galaxy_tags:
    - docker
    - compose
    - container

dependencies: []