---
- name: Create groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ groups_list }}"
  tags: ['groups_list']

- name: Create users
  ansible.builtin.user:
    name: "{{ item.username }}"
    comment: "{{ item.comment | default(omit) }}"
    shell: "{{ item.shell | default(default_shell) }}"
    groups: "{{ item.groups | default([]) | join(',') }}"
    append: yes
    state: "{{ item.state | default('present') }}"
    remove: "{{ remove_home if item.state | default('present') == 'absent' else omit }}"
    createhome: yes
  loop: "{{ users }}"
  tags: ['users']

- name: Set up SSH keys
  ansible.builtin.authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.ssh_key }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ users }}"
  when: item.ssh_key is defined and item.state | default('present') == 'present'
  tags: ['ssh-keys']
