---
galaxy_info:
  author: Keuleu Royce
  description: Server patching role for Debian/Ubuntu and RedHat/CentOS systems
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - system
    - patching
    - security