# roles/docker/tasks/main.yml
---
- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg
      - python3-pip
    state: present
    update_cache: yes
  become: true

- name: Add Docker GPG key
  block:
    - name: Ensure /etc/apt/keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      
    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker.gpg
        mode: '0644'

    - name: Dearmor and save Docker GPG key
      shell: gpg --dearmor < /tmp/docker.gpg > /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Set correct permissions for GPG key
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'
  become: true

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: yes
  become: true

- name: Install Docker packages
  apt:
    name:
      - docker.io
    state: present
    update_cache: yes
  become: true

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Create docker group
  group:
    name: docker
    state: present
  become: true

- name: Add user to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
  when: docker_user is defined
  become: true

- name: Ensure Python venv is installed
  apt:
    name: python3-venv
    state: present
  become: true

- name: Create a Python virtual environment
  command: python3 -m venv /opt/venv
  args:
    creates: /opt/venv
  become: true

- name: Install Docker Python package in the virtual environment
  pip:
    name: docker
    state: present
    virtualenv: /opt/venv
  when: install_python_docker | default(true)
  become: true
