---
- name: Install Apache
  ansible.builtin.package:
    name: "{{ apache_package }}"
    state: present
  vars:
    apache_package: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"

- name: Create document root
  ansible.builtin.file:
    path: "{{ webserver_document_root }}"
    state: directory
    mode: '0755'

- name: Configure Apache
  ansible.builtin.template:
    src: "{{ 'apache2.conf.j2' if ansible_os_family == 'Debian' else 'httpd.conf.j2' }}"
    dest: "{{ '/etc/apache2/apache2.conf' if ansible_os_family == 'Debian' else '/etc/httpd/conf/httpd.conf' }}"
    mode: '0644'
  notify: restart apache

- name: Enable Apache modules
  ansible.builtin.apache2_module:
    name: "{{ item }}"
    state: present
  loop: "{{ apache_mods_enabled }}"
  when: ansible_os_family == 'Debian'
  notify: restart apache

- name: Create default index page
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ webserver_document_root }}/index.html"
    mode: '0644'
  when: default_page_enabled

- name: Stop Nginx service
  ansible.builtin.service:
    name: nginx
    state: stopped


- name: Start and enable Apache
  ansible.builtin.service:
    name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    state: started
    enabled: yes