---
- name: reboot_if_needed
  ansible.builtin.reboot:
    msg: "Reboot triggered by package upgrade"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
  when: 
    - reboot_required is defined
    - reboot_required
    - auto_reboot | default(false)
