# roles/docker/meta/main.yml
---
galaxy_info:
  author: Your Name
  description: Install Docker CE
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - 7
        - 8
        - 9
  galaxy_tags:
    - docker
    - container

dependencies: []